# Default values for storedq-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.grandsys.com/inu/storedq-domain
  tag: ${BUILD_TAG}
  pullPolicy: IfNotPresent
  pullSecret: grandsys
resources:
  limits:
    memory: 1Gi

actorsystem: demo1
seedPort: 2551
clusterHttpManPort: 7878
seedrole: seed
seednodes:
  replicaCount: 2
  service:
    name: akka-seeds
  hostnamePrefix: akka-seed

helmRepo: grandsys

